### ISSUE TITLE
OfflineDataInfo does not contain page count information

### ISSUE THREAD

**Issue by inkmike** [NeoSmartpen/WindowSDK2.0#4]
One of the things we'd like our implementation to do is return all the data from the device in a single request - meaning that our implementation has to know how much data to expect from the SDK so it knows when to finish and return the final result.

When calling ReqOfflineDataList, the returned OfflineDataInfo objects always has a null 'Pages' attribute. This means that when we call PenComm.ReqOfflineData, we are unsure how many times we will receive the onReceiveOfflineStrokes callback (as this callback appears to be triggered once for every page) - at this point we have no way of knowing how many pages that note contains. 

_Some additional information:
Device model: NWP-F110
Device class: 1280 (V1)_

Is it possible to retrieve the number of pages per note? Alternatively, is there some sort of indicator to identify the final onReceiveOfflineStrokes callback?

**Comment by chyccs** [comment]
Hi inkmake,

Pages attribute is not supported for NWP-F110.
and we can't indicate when called final onReceiveOfflineStrokes callback. 

If your offline data is in one page, but you have a lot of writing
  The onReceiveOfflineStrokes callback can be called many times. This is because the maximum amount of data that can be transmitted at one time is fixed.

It is recommended that you refer to this callback method since the onFinishedOfflineDownload callback is called when the data transfer is finished.

**Comment by inkmike** [comment]
Thanks, the onFinishedOfflineDownload is exactly what was needed.
